version: 2
jobs:
  "任务1":
    docker:
      - image: circleci/node:4.8.2

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
  "任务2":
    docker:
      - image: circleci/node:4.8.2

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
      
      
  "任务3":
    docker:
      - image: circleci/node:4.8.2

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
          
      - store_test_results:
          path: test-results
          
  "任务4":
    docker:
      - image: circleci/node:4.8.2

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
          
      - store_test_results:
          path: test-results
          
workflows:
  version: 2
  "自定义工作流": # name of your workflow
    jobs:
      - "任务1"
      
      - "任务2":
          requires:
            - "任务1"

      - "任务3":

      - "任务4":
          requires:
            - "任务2"
            - "任务1"
          type: approval
