version: 2
jobs:
  任务1:
    docker:
      - image: circleci/node:4.8.2

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
  任务2:
    docker:
      - image: circleci/node:4.8.2

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
  任务3:
    docker:
      - image: circleci/node:4.8.2

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
workflows:
  version: 2
  build_and_test: # name of your workflow
    jobs:
      - 任务1
      - 任务2:
        requires:
           - 任务1 # wait for build1 job to complete successfully before starting
           # see circleci.com/docs/2.0/workflows/ for more examples.
      - 任务3:
        requires:
           - 任务1 # wait for build1 job to complete successfully before starting
           # run build2 and build3 in parallel to save time.
